name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'


stages:

- stage: unitTests
  displayName: Run Unit Tests
  jobs:
  - job: unitTests
    displayName: Run Unit Tests
    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
        Python38:
          PYTHON_VERSION: '3.8'
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'


    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
        displayName: Use Python $(PYTHON_VERSION)

      - script: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.1
        displayName: 'Install poetry 1.4.1'
      
      - script: python -m poetry install
        displayName: 'Install dependencies'
        
      - script: python -m poetry run python -m pytest
        displayName: 'Test with pytest'